plugins:
  - "@trivago/prettier-plugin-sort-imports"
  - "prettier-plugin-solidity"
arrowParens: avoid
bracketSpacing: true
printWidth: 100
semi: false
singleQuote: true
trailingComma: 'es5'

# Solidity official style guid
# https://docs.soliditylang.org/en/v0.8.18/style-guide.html
overrides:
  - files: '*.sol'
    options:
      compiler: "0.8.17"
      tabWidth: 4
      singleQuote: false
      parser: "solidity-parse"

  - files: "*.ts"
    options:
      importOrder: ["^node:", "<THIRD_PARTY_MODULES>", "^~", "^[./]", "^import type"]
      importOrderSeparation: true
      importOrderSortSpecifiers: true
      importOrderGroupNamespaceSpecifiers: true
      parser: "typescript"
